# Generated by Django 5.2.7 on 2025-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_update_status_choices_add_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='governorate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
