# Generated by Django 5.2.7 on 2025-12-03 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seller',
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
