# Generated by Django 5.2.7 on 2025-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_governorate'),
        ('users', '0003_user_location'),
    ]

    operations = [
    ]
